### ISSUE TITLE
Watch out for read values of Bolt outside a transaction

### ISSUE THREAD

**Issue by rgl** [github/lfs-test-server#15]
At https://github.com/github/lfs-test-server/blob/master/meta_store.go#L68 (MetaStore.Get) you are using a value outside a transaction. This should not be done, see the bolt docs at:

> Please note that values returned from Get() are only valid while the transaction is open. If you need to use a value outside of the transaction then you must use copy() to copy it to another byte slice.

**Comment by shiftkey** [comment]
@rgl this seems like a easy fix - would you be interested in submitting a PR?

**Comment by rgl** [comment]
Its at https://github.com/github/lfs-test-server/pull/19

**Comment by rubyist** [comment]
Merged in, thanks!
