### ISSUE TITLE
management page in server reports funny url if running over http instead of https

### ISSUE THREAD

**Issue by lbergelson** [github/lfs-test-server#26]
If running the server over http instead of https the management UI page reports an invalid URL to use in your `.gitconfig` .  It's missing the `http`
![screen shot 2015-05-05 at 1 13 50 pm](https://cloud.githubusercontent.com/assets/4700332/7478392/984fc960-f328-11e4-88c7-6efb43569690.png)

**Comment by rubyist** [comment]
Fixed this up in #28, thanks for the report!

**Comment by Jericho25** [comment]
Thanks man and please make it modern....Ciao!       #jgaj
