### ISSUE TITLE
Have to enter password twice during git clone

### ISSUE THREAD

**Issue by curzona** [github/lfs-test-server#41]
Have to enter password twice during git clone. 

```
$ git clone ../repo.git
Cloning into 'repo'...
done.
Downloading sound.mp3 (4.80 MB)
Username for 'http://127.0.0.1:9999': fred
Password for 'http://fred@127.0.0.1:9999': 
Username for 'http://127.0.0.1:9999': fred
Password for 'http://fred@127.0.0.1:9999': 
```

**Comment by swolfish** [comment]
Same problem here.
As many files you've tracked so many times you're prompted for user and pass.

**Comment by rubyist** [comment]
Hi, are you using one of git's [credential cachers](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage)? If not, you will be prompted for credentials each time. We recommend setting up a credential cache to avoid this.

**Comment by curzona** [comment]
@rubyist After I configured credential caching I only get prompted once. Thanks.
